//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rail.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string MainAll {
            get {
                return ResourceManager.GetString("MainAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string MainAngle {
            get {
                return ResourceManager.GetString("MainAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle (°).
        /// </summary>
        public static string MainAngleDeg {
            get {
                return ResourceManager.GetString("MainAngleDeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string MainArticle {
            get {
                return ResourceManager.GetString("MainArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string MainClipboard {
            get {
                return ResourceManager.GetString("MainClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MainCopy {
            get {
                return ResourceManager.GetString("MainCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Groups.
        /// </summary>
        public static string MainCustomer {
            get {
                return ResourceManager.GetString("MainCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string MainCut {
            get {
                return ResourceManager.GetString("MainCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MainDelete {
            get {
                return ResourceManager.GetString("MainDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string MainDuplicate {
            get {
                return ResourceManager.GetString("MainDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ....
        /// </summary>
        public static string MainFileAbout {
            get {
                return ResourceManager.GetString("MainFileAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainFileExit {
            get {
                return ResourceManager.GetString("MainFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help ....
        /// </summary>
        public static string MainFileHelp {
            get {
                return ResourceManager.GetString("MainFileHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainFileNew {
            get {
                return ResourceManager.GetString("MainFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ....
        /// </summary>
        public static string MainFileOpen {
            get {
                return ResourceManager.GetString("MainFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print ....
        /// </summary>
        public static string MainFilePrint {
            get {
                return ResourceManager.GetString("MainFilePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview ....
        /// </summary>
        public static string MainFilePrintPreview {
            get {
                return ResourceManager.GetString("MainFilePrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string MainFileRecentFiles {
            get {
                return ResourceManager.GetString("MainFileRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainFileSave {
            get {
                return ResourceManager.GetString("MainFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As ....
        /// </summary>
        public static string MainFileSaveAs {
            get {
                return ResourceManager.GetString("MainFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauge.
        /// </summary>
        public static string MainGauge {
            get {
                return ResourceManager.GetString("MainGauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient (%).
        /// </summary>
        public static string MainGradientPerc {
            get {
                return ResourceManager.GetString("MainGradientPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string MainGroup {
            get {
                return ResourceManager.GetString("MainGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string MainGroupCreate {
            get {
                return ResourceManager.GetString("MainGroupCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        public static string MainGroupResolve {
            get {
                return ResourceManager.GetString("MainGroupResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Group As....
        /// </summary>
        public static string MainGroupSaveAs {
            get {
                return ResourceManager.GetString("MainGroupSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string MainGroupTitle {
            get {
                return ResourceManager.GetString("MainGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (mm).
        /// </summary>
        public static string MainHeightmm {
            get {
                return ResourceManager.GetString("MainHeightmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Helix.
        /// </summary>
        public static string MainHelixCreate {
            get {
                return ResourceManager.GetString("MainHelixCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve Helix.
        /// </summary>
        public static string MainHelixDelete {
            get {
                return ResourceManager.GetString("MainHelixDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Helix.
        /// </summary>
        public static string MainHelixEdit {
            get {
                return ResourceManager.GetString("MainHelixEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helixes.
        /// </summary>
        public static string MainHelixTitle {
            get {
                return ResourceManager.GetString("MainHelixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string MainHistory {
            get {
                return ResourceManager.GetString("MainHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string MainLayer {
            get {
                return ResourceManager.GetString("MainLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Name.
        /// </summary>
        public static string MainLayerName {
            get {
                return ResourceManager.GetString("MainLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string MainLayers {
            get {
                return ResourceManager.GetString("MainLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Rail.
        /// </summary>
        public static string MainLockLock {
            get {
                return ResourceManager.GetString("MainLockLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string MainLockTitle {
            get {
                return ResourceManager.GetString("MainLockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Rail.
        /// </summary>
        public static string MainLockUnlock {
            get {
                return ResourceManager.GetString("MainLockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string MainManufacturer {
            get {
                return ResourceManager.GetString("MainManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material List.
        /// </summary>
        public static string MainMaterialList {
            get {
                return ResourceManager.GetString("MainMaterialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MainName {
            get {
                return ResourceManager.GetString("MainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        public static string MainOptions {
            get {
                return ResourceManager.GetString("MainOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string MainPaste {
            get {
                return ResourceManager.GetString("MainPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string MainPlan {
            get {
                return ResourceManager.GetString("MainPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string MainPosition {
            get {
                return ResourceManager.GetString("MainPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail.
        /// </summary>
        public static string MainRail {
            get {
                return ResourceManager.GetString("MainRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail Plan.
        /// </summary>
        public static string MainRailPlan {
            get {
                return ResourceManager.GetString("MainRailPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ramp.
        /// </summary>
        public static string MainRampCreate {
            get {
                return ResourceManager.GetString("MainRampCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Ramp.
        /// </summary>
        public static string MainRampDelete {
            get {
                return ResourceManager.GetString("MainRampDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MainRampEdit {
            get {
                return ResourceManager.GetString("MainRampEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramps.
        /// </summary>
        public static string MainRampTitle {
            get {
                return ResourceManager.GetString("MainRampTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string MainRedo {
            get {
                return ResourceManager.GetString("MainRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string MainRotation {
            get {
                return ResourceManager.GetString("MainRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectAll.
        /// </summary>
        public static string MainSelectAll {
            get {
                return ResourceManager.GetString("MainSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string MainShow {
            get {
                return ResourceManager.GetString("MainShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Clear Space.
        /// </summary>
        public static string MainShowClearSpace {
            get {
                return ResourceManager.GetString("MainShowClearSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Docking Points.
        /// </summary>
        public static string MainShowDockingPoints {
            get {
                return ResourceManager.GetString("MainShowDockingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Track List.
        /// </summary>
        public static string MainShowTrackList {
            get {
                return ResourceManager.GetString("MainShowTrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string MainSingle {
            get {
                return ResourceManager.GetString("MainSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches.
        /// </summary>
        public static string MainSwitches {
            get {
                return ResourceManager.GetString("MainSwitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        public static string MainTerrain {
            get {
                return ResourceManager.GetString("MainTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt.
        /// </summary>
        public static string MainTilt {
            get {
                return ResourceManager.GetString("MainTilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MainTools {
            get {
                return ResourceManager.GetString("MainTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string MainTracks {
            get {
                return ResourceManager.GetString("MainTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string MainUndo {
            get {
                return ResourceManager.GetString("MainUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Distance.
        /// </summary>
        public static string MainViewGridDistance {
            get {
                return ResourceManager.GetString("MainViewGridDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Modes.
        /// </summary>
        public static string MainViewModes {
            get {
                return ResourceManager.GetString("MainViewModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap In Angle.
        /// </summary>
        public static string MainViewSnapInAngle {
            get {
                return ResourceManager.GetString("MainViewSnapInAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap In Distance.
        /// </summary>
        public static string MainViewSnapInDistance {
            get {
                return ResourceManager.GetString("MainViewSnapInDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MainViewTitle {
            get {
                return ResourceManager.GetString("MainViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X (mm).
        /// </summary>
        public static string MainXmm {
            get {
                return ResourceManager.GetString("MainXmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y (mm).
        /// </summary>
        public static string MainYmm {
            get {
                return ResourceManager.GetString("MainYmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string MainZoom {
            get {
                return ResourceManager.GetString("MainZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta X.
        /// </summary>
        public static string MeasureDeltaX {
            get {
                return ResourceManager.GetString("MeasureDeltaX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Y.
        /// </summary>
        public static string MeasureDeltaY {
            get {
                return ResourceManager.GetString("MeasureDeltaY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string MeasureDistance {
            get {
                return ResourceManager.GetString("MeasureDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string MeasureMM {
            get {
                return ResourceManager.GetString("MeasureMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Measurement.
        /// </summary>
        public static string MeasureTitle {
            get {
                return ResourceManager.GetString("MeasureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string MenuProperties {
            get {
                return ResourceManager.GetString("MenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string MenuRotate {
            get {
                return ResourceManager.GetString("MenuRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kink Angle (%).
        /// </summary>
        public static string OptionsKinkAngle {
            get {
                return ResourceManager.GetString("OptionsKinkAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string OptionsLanguage {
            get {
                return ResourceManager.GetString("OptionsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Pitch (%).
        /// </summary>
        public static string OptionsMaximumPitch {
            get {
                return ResourceManager.GetString("OptionsMaximumPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp.
        /// </summary>
        public static string OptionsRamp {
            get {
                return ResourceManager.GetString("OptionsRamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible after restart.
        /// </summary>
        public static string OptionsVisibleAfterRestart {
            get {
                return ResourceManager.GetString("OptionsVisibleAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail Plan View.
        /// </summary>
        public static string RailPlanView {
            get {
                return ResourceManager.GetString("RailPlanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kink Angle.
        /// </summary>
        public static string RampKinkAngle {
            get {
                return ResourceManager.GetString("RampKinkAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Height.
        /// </summary>
        public static string RampLayerHeight {
            get {
                return ResourceManager.GetString("RampLayerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Pitch.
        /// </summary>
        public static string RampMaximumPitch {
            get {
                return ResourceManager.GetString("RampMaximumPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter Track.
        /// </summary>
        public static string TrackAdapter {
            get {
                return ResourceManager.GetString("TrackAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track End with a Bumper.
        /// </summary>
        public static string TrackBumper {
            get {
                return ResourceManager.GetString("TrackBumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossing.
        /// </summary>
        public static string TrackCrossing {
            get {
                return ResourceManager.GetString("TrackCrossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Track.
        /// </summary>
        public static string TrackCurved {
            get {
                return ResourceManager.GetString("TrackCurved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Circuit Track.
        /// </summary>
        public static string TrackCurvedCircuit {
            get {
                return ResourceManager.GetString("TrackCurvedCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Curved Turnout.
        /// </summary>
        public static string TrackCurvedTurnoutLeft {
            get {
                return ResourceManager.GetString("TrackCurvedTurnoutLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Curved Turnout.
        /// </summary>
        public static string TrackCurvedTurnoutRight {
            get {
                return ResourceManager.GetString("TrackCurvedTurnoutRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Crossover.
        /// </summary>
        public static string TrackDoubleCrossover {
            get {
                return ResourceManager.GetString("TrackDoubleCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Slip Switch.
        /// </summary>
        public static string TrackDoubleSlipSwitch {
            get {
                return ResourceManager.GetString("TrackDoubleSlipSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-Way Turnout.
        /// </summary>
        public static string TrackDoubleTurnout {
            get {
                return ResourceManager.GetString("TrackDoubleTurnout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electrical.
        /// </summary>
        public static string TrackDriveElectrical {
            get {
                return ResourceManager.GetString("TrackDriveElectrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mechanical.
        /// </summary>
        public static string TrackDriveMechanical {
            get {
                return ResourceManager.GetString("TrackDriveMechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Piece with Track Roadbed.
        /// </summary>
        public static string TrackEndPiece {
            get {
                return ResourceManager.GetString("TrackEndPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flex Track.
        /// </summary>
        public static string TrackFlex {
            get {
                return ResourceManager.GetString("TrackFlex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Track.
        /// </summary>
        public static string TrackStraight {
            get {
                return ResourceManager.GetString("TrackStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Adjustment.
        /// </summary>
        public static string TrackStraightAdjustment {
            get {
                return ResourceManager.GetString("TrackStraightAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Circuit Track.
        /// </summary>
        public static string TrackStraightCircuit {
            get {
                return ResourceManager.GetString("TrackStraightCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Track.
        /// </summary>
        public static string TrackStraightContact {
            get {
                return ResourceManager.GetString("TrackStraightContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Feeder.
        /// </summary>
        public static string TrackStraightFeeder {
            get {
                return ResourceManager.GetString("TrackStraightFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Isolating.
        /// </summary>
        public static string TrackStraightIsolating {
            get {
                return ResourceManager.GetString("TrackStraightIsolating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Uncoupler.
        /// </summary>
        public static string TrackStraightUncoupler {
            get {
                return ResourceManager.GetString("TrackStraightUncoupler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Table.
        /// </summary>
        public static string TrackTransferTable {
            get {
                return ResourceManager.GetString("TrackTransferTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Turnout.
        /// </summary>
        public static string TrackTurnoutLeft {
            get {
                return ResourceManager.GetString("TrackTurnoutLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Turnout.
        /// </summary>
        public static string TrackTurnoutRight {
            get {
                return ResourceManager.GetString("TrackTurnoutRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turntable.
        /// </summary>
        public static string TrackTurntable {
            get {
                return ResourceManager.GetString("TrackTurntable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with a lantern.
        /// </summary>
        public static string TrackWithLantern {
            get {
                return ResourceManager.GetString("TrackWithLantern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Turnout.
        /// </summary>
        public static string TrackYTurnout {
            get {
                return ResourceManager.GetString("TrackYTurnout", resourceCulture);
            }
        }
    }
}
