//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rail.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string MainAngle {
            get {
                return ResourceManager.GetString("MainAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string MainArticle {
            get {
                return ResourceManager.GetString("MainArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Groups.
        /// </summary>
        public static string MainCustomer {
            get {
                return ResourceManager.GetString("MainCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string MainDistance {
            get {
                return ResourceManager.GetString("MainDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ....
        /// </summary>
        public static string MainFileAbout {
            get {
                return ResourceManager.GetString("MainFileAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainFileExit {
            get {
                return ResourceManager.GetString("MainFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help ....
        /// </summary>
        public static string MainFileHelp {
            get {
                return ResourceManager.GetString("MainFileHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainFileNew {
            get {
                return ResourceManager.GetString("MainFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ....
        /// </summary>
        public static string MainFileOpen {
            get {
                return ResourceManager.GetString("MainFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print ....
        /// </summary>
        public static string MainFilePrint {
            get {
                return ResourceManager.GetString("MainFilePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview ....
        /// </summary>
        public static string MainFilePrintPreview {
            get {
                return ResourceManager.GetString("MainFilePrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string MainFileRecentFiles {
            get {
                return ResourceManager.GetString("MainFileRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainFileSave {
            get {
                return ResourceManager.GetString("MainFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As ....
        /// </summary>
        public static string MainFileSaveAs {
            get {
                return ResourceManager.GetString("MainFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Lines.
        /// </summary>
        public static string MainGridLines {
            get {
                return ResourceManager.GetString("MainGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string MainGroup {
            get {
                return ResourceManager.GetString("MainGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Layer.
        /// </summary>
        public static string MainInsertLayer {
            get {
                return ResourceManager.GetString("MainInsertLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string MainLayer {
            get {
                return ResourceManager.GetString("MainLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string MainManufacturer {
            get {
                return ResourceManager.GetString("MainManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MainName {
            get {
                return ResourceManager.GetString("MainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string MainPlan {
            get {
                return ResourceManager.GetString("MainPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string MainPosition {
            get {
                return ResourceManager.GetString("MainPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail.
        /// </summary>
        public static string MainRail {
            get {
                return ResourceManager.GetString("MainRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail Plan.
        /// </summary>
        public static string MainRailPlan {
            get {
                return ResourceManager.GetString("MainRailPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string MainRotation {
            get {
                return ResourceManager.GetString("MainRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Docking Points.
        /// </summary>
        public static string MainShowDockingPoints {
            get {
                return ResourceManager.GetString("MainShowDockingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Layer.
        /// </summary>
        public static string MainShowLayer {
            get {
                return ResourceManager.GetString("MainShowLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Track List.
        /// </summary>
        public static string MainShowTrackList {
            get {
                return ResourceManager.GetString("MainShowTrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string MainSingle {
            get {
                return ResourceManager.GetString("MainSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap In.
        /// </summary>
        public static string MainSnapIn {
            get {
                return ResourceManager.GetString("MainSnapIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches.
        /// </summary>
        public static string MainSwitches {
            get {
                return ResourceManager.GetString("MainSwitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        public static string MainTerrain {
            get {
                return ResourceManager.GetString("MainTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt.
        /// </summary>
        public static string MainTilt {
            get {
                return ResourceManager.GetString("MainTilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string MainTracks {
            get {
                return ResourceManager.GetString("MainTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Modes.
        /// </summary>
        public static string MainViewModes {
            get {
                return ResourceManager.GetString("MainViewModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string MainZoom {
            get {
                return ResourceManager.GetString("MainZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail Plan View.
        /// </summary>
        public static string RailPlanView {
            get {
                return ResourceManager.GetString("RailPlanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter Track.
        /// </summary>
        public static string TrackAdapter {
            get {
                return ResourceManager.GetString("TrackAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track End with a Bumper.
        /// </summary>
        public static string TrackBumper {
            get {
                return ResourceManager.GetString("TrackBumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossing.
        /// </summary>
        public static string TrackCrossing {
            get {
                return ResourceManager.GetString("TrackCrossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Track.
        /// </summary>
        public static string TrackCurved {
            get {
                return ResourceManager.GetString("TrackCurved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Circuit Track.
        /// </summary>
        public static string TrackCurvedCircuit {
            get {
                return ResourceManager.GetString("TrackCurvedCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Curved Turnout.
        /// </summary>
        public static string TrackCurvedTurnoutLeft {
            get {
                return ResourceManager.GetString("TrackCurvedTurnoutLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Curved Turnout.
        /// </summary>
        public static string TrackCurvedTurnoutRight {
            get {
                return ResourceManager.GetString("TrackCurvedTurnoutRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Slip Switch.
        /// </summary>
        public static string TrackDoubleSlipSwitch {
            get {
                return ResourceManager.GetString("TrackDoubleSlipSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-Way Turnout.
        /// </summary>
        public static string TrackDoubleTurnout {
            get {
                return ResourceManager.GetString("TrackDoubleTurnout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electrical.
        /// </summary>
        public static string TrackDriveElectrical {
            get {
                return ResourceManager.GetString("TrackDriveElectrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mechanical.
        /// </summary>
        public static string TrackDriveMechanical {
            get {
                return ResourceManager.GetString("TrackDriveMechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Piece with Track Roadbed.
        /// </summary>
        public static string TrackEndPiece {
            get {
                return ResourceManager.GetString("TrackEndPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flex Track.
        /// </summary>
        public static string TrackFlex {
            get {
                return ResourceManager.GetString("TrackFlex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Track.
        /// </summary>
        public static string TrackStraight {
            get {
                return ResourceManager.GetString("TrackStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Adjustment.
        /// </summary>
        public static string TrackStraightAdjustment {
            get {
                return ResourceManager.GetString("TrackStraightAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Circuit Track.
        /// </summary>
        public static string TrackStraightCircuit {
            get {
                return ResourceManager.GetString("TrackStraightCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Track.
        /// </summary>
        public static string TrackStraightContact {
            get {
                return ResourceManager.GetString("TrackStraightContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Feeder.
        /// </summary>
        public static string TrackStraightFeeder {
            get {
                return ResourceManager.GetString("TrackStraightFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Isolating.
        /// </summary>
        public static string TrackStraightIsolating {
            get {
                return ResourceManager.GetString("TrackStraightIsolating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Uncoupler.
        /// </summary>
        public static string TrackStraightUncoupler {
            get {
                return ResourceManager.GetString("TrackStraightUncoupler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspender.
        /// </summary>
        public static string TrackSuspender {
            get {
                return ResourceManager.GetString("TrackSuspender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Table.
        /// </summary>
        public static string TrackTransferTable {
            get {
                return ResourceManager.GetString("TrackTransferTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Turnout.
        /// </summary>
        public static string TrackTurnoutLeft {
            get {
                return ResourceManager.GetString("TrackTurnoutLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Turnout.
        /// </summary>
        public static string TrackTurnoutRight {
            get {
                return ResourceManager.GetString("TrackTurnoutRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turntable.
        /// </summary>
        public static string TrackTurntable {
            get {
                return ResourceManager.GetString("TrackTurntable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with a lantern.
        /// </summary>
        public static string TrackWithLantern {
            get {
                return ResourceManager.GetString("TrackWithLantern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Turnout.
        /// </summary>
        public static string TrackYTurnout {
            get {
                return ResourceManager.GetString("TrackYTurnout", resourceCulture);
            }
        }
    }
}
