//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail.Tracks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rail.Tracks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter.
        /// </summary>
        public static string EnumAdapter {
            get {
                return ResourceManager.GetString("EnumAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        public static string EnumAdjustment {
            get {
                return ResourceManager.GetString("EnumAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string EnumBlack {
            get {
                return ResourceManager.GetString("EnumBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brass.
        /// </summary>
        public static string EnumBrass {
            get {
                return ResourceManager.GetString("EnumBrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumper.
        /// </summary>
        public static string EnumBumper {
            get {
                return ResourceManager.GetString("EnumBumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumper with Lantern.
        /// </summary>
        public static string EnumBumperWithLantern {
            get {
                return ResourceManager.GetString("EnumBumperWithLantern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit.
        /// </summary>
        public static string EnumCircuit {
            get {
                return ResourceManager.GetString("EnumCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete.
        /// </summary>
        public static string EnumConcrete {
            get {
                return ResourceManager.GetString("EnumConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string EnumContact {
            get {
                return ResourceManager.GetString("EnumContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical.
        /// </summary>
        public static string EnumElectricali {
            get {
                return ResourceManager.GetString("EnumElectricali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumEnd.
        /// </summary>
        public static string EnumEnd {
            get {
                return ResourceManager.GetString("EnumEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeder.
        /// </summary>
        public static string EnumFeeder {
            get {
                return ResourceManager.GetString("EnumFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flex.
        /// </summary>
        public static string EnumFlex {
            get {
                return ResourceManager.GetString("EnumFlex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolating.
        /// </summary>
        public static string EnumIsolating {
            get {
                return ResourceManager.GetString("EnumIsolating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string EnumLeft {
            get {
                return ResourceManager.GetString("EnumLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanical.
        /// </summary>
        public static string EnumMechanical {
            get {
                return ResourceManager.GetString("EnumMechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string EnumNo {
            get {
                return ResourceManager.GetString("EnumNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string EnumRight {
            get {
                return ResourceManager.GetString("EnumRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string EnumSilver {
            get {
                return ResourceManager.GetString("EnumSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncoupler.
        /// </summary>
        public static string EnumUncoupler {
            get {
                return ResourceManager.GetString("EnumUncoupler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string EnumUnknown {
            get {
                return ResourceManager.GetString("EnumUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden.
        /// </summary>
        public static string EnumWooden {
            get {
                return ResourceManager.GetString("EnumWooden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string EnumY {
            get {
                return ResourceManager.GetString("EnumY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter Track.
        /// </summary>
        public static string TrackAdapter {
            get {
                return ResourceManager.GetString("TrackAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track End with a Bumper.
        /// </summary>
        public static string TrackBumper {
            get {
                return ResourceManager.GetString("TrackBumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumper with a lantern.
        /// </summary>
        public static string TrackBumperWithLantern {
            get {
                return ResourceManager.GetString("TrackBumperWithLantern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossing.
        /// </summary>
        public static string TrackCrossing {
            get {
                return ResourceManager.GetString("TrackCrossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Track.
        /// </summary>
        public static string TrackCurved {
            get {
                return ResourceManager.GetString("TrackCurved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Circuit Track.
        /// </summary>
        public static string TrackCurvedCircuit {
            get {
                return ResourceManager.GetString("TrackCurvedCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Contact Track.
        /// </summary>
        public static string TrackCurvedContact {
            get {
                return ResourceManager.GetString("TrackCurvedContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Feeder.
        /// </summary>
        public static string TrackCurvedFeeder {
            get {
                return ResourceManager.GetString("TrackCurvedFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Isolating.
        /// </summary>
        public static string TrackCurvedIsolating {
            get {
                return ResourceManager.GetString("TrackCurvedIsolating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Curved Turnout.
        /// </summary>
        public static string TrackCurvedTurnoutLeft {
            get {
                return ResourceManager.GetString("TrackCurvedTurnoutLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Curved Turnout.
        /// </summary>
        public static string TrackCurvedTurnoutRight {
            get {
                return ResourceManager.GetString("TrackCurvedTurnoutRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Uncoupler.
        /// </summary>
        public static string TrackCurvedUncoupler {
            get {
                return ResourceManager.GetString("TrackCurvedUncoupler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Crossover.
        /// </summary>
        public static string TrackDoubleCrossover {
            get {
                return ResourceManager.GetString("TrackDoubleCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Slip Switch.
        /// </summary>
        public static string TrackDoubleSlipSwitch {
            get {
                return ResourceManager.GetString("TrackDoubleSlipSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electrical.
        /// </summary>
        public static string TrackDriveElectrical {
            get {
                return ResourceManager.GetString("TrackDriveElectrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mechanical.
        /// </summary>
        public static string TrackDriveMechanical {
            get {
                return ResourceManager.GetString("TrackDriveMechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Piece with Track Roadbed.
        /// </summary>
        public static string TrackEndPiece {
            get {
                return ResourceManager.GetString("TrackEndPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flex Track.
        /// </summary>
        public static string TrackFlex {
            get {
                return ResourceManager.GetString("TrackFlex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string TrackLeft_del {
            get {
                return ResourceManager.GetString("TrackLeft_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string TrackRight_del {
            get {
                return ResourceManager.GetString("TrackRight_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Track.
        /// </summary>
        public static string TrackStraight {
            get {
                return ResourceManager.GetString("TrackStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Circuit Track.
        /// </summary>
        public static string TrackStraightCircuit {
            get {
                return ResourceManager.GetString("TrackStraightCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Contact Track.
        /// </summary>
        public static string TrackStraightContact {
            get {
                return ResourceManager.GetString("TrackStraightContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Feeder.
        /// </summary>
        public static string TrackStraightFeeder {
            get {
                return ResourceManager.GetString("TrackStraightFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Isolating.
        /// </summary>
        public static string TrackStraightIsolating {
            get {
                return ResourceManager.GetString("TrackStraightIsolating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Uncoupler.
        /// </summary>
        public static string TrackStraightUncoupler {
            get {
                return ResourceManager.GetString("TrackStraightUncoupler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string TrackThree {
            get {
                return ResourceManager.GetString("TrackThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-Way Turnout.
        /// </summary>
        public static string TrackThreeWayTurnout {
            get {
                return ResourceManager.GetString("TrackThreeWayTurnout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Table.
        /// </summary>
        public static string TrackTransferTable {
            get {
                return ResourceManager.GetString("TrackTransferTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Turnout.
        /// </summary>
        public static string TrackTurnoutLeft {
            get {
                return ResourceManager.GetString("TrackTurnoutLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Turnout.
        /// </summary>
        public static string TrackTurnoutRight {
            get {
                return ResourceManager.GetString("TrackTurnoutRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turntable.
        /// </summary>
        public static string TrackTurntable {
            get {
                return ResourceManager.GetString("TrackTurntable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string TrackY {
            get {
                return ResourceManager.GetString("TrackY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Turnout.
        /// </summary>
        public static string TrackYTurnout {
            get {
                return ResourceManager.GetString("TrackYTurnout", resourceCulture);
            }
        }
    }
}
