//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail.Tracks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rail.Tracks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter Track.
        /// </summary>
        public static string TrackAdapter {
            get {
                return ResourceManager.GetString("TrackAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track End with a Bumper.
        /// </summary>
        public static string TrackBumper {
            get {
                return ResourceManager.GetString("TrackBumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossing.
        /// </summary>
        public static string TrackCrossing {
            get {
                return ResourceManager.GetString("TrackCrossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Track.
        /// </summary>
        public static string TrackCurved {
            get {
                return ResourceManager.GetString("TrackCurved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Circuit Track.
        /// </summary>
        public static string TrackCurvedCircuit {
            get {
                return ResourceManager.GetString("TrackCurvedCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Contact Track.
        /// </summary>
        public static string TrackCurvedContact {
            get {
                return ResourceManager.GetString("TrackCurvedContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Feeder.
        /// </summary>
        public static string TrackCurvedFeeder {
            get {
                return ResourceManager.GetString("TrackCurvedFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Isolating.
        /// </summary>
        public static string TrackCurvedIsolating {
            get {
                return ResourceManager.GetString("TrackCurvedIsolating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Curved Turnout.
        /// </summary>
        public static string TrackCurvedTurnoutLeft {
            get {
                return ResourceManager.GetString("TrackCurvedTurnoutLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Curved Turnout.
        /// </summary>
        public static string TrackCurvedTurnoutRight {
            get {
                return ResourceManager.GetString("TrackCurvedTurnoutRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Uncoupler.
        /// </summary>
        public static string TrackCurvedUncoupler {
            get {
                return ResourceManager.GetString("TrackCurvedUncoupler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Crossover.
        /// </summary>
        public static string TrackDoubleCrossover {
            get {
                return ResourceManager.GetString("TrackDoubleCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Slip Switch.
        /// </summary>
        public static string TrackDoubleSlipSwitch {
            get {
                return ResourceManager.GetString("TrackDoubleSlipSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electrical.
        /// </summary>
        public static string TrackDriveElectrical {
            get {
                return ResourceManager.GetString("TrackDriveElectrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mechanical.
        /// </summary>
        public static string TrackDriveMechanical {
            get {
                return ResourceManager.GetString("TrackDriveMechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Piece with Track Roadbed.
        /// </summary>
        public static string TrackEndPiece {
            get {
                return ResourceManager.GetString("TrackEndPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flex Track.
        /// </summary>
        public static string TrackFlex {
            get {
                return ResourceManager.GetString("TrackFlex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Track.
        /// </summary>
        public static string TrackStraight {
            get {
                return ResourceManager.GetString("TrackStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Adjustment.
        /// </summary>
        public static string TrackStraightAdjustment {
            get {
                return ResourceManager.GetString("TrackStraightAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Circuit Track.
        /// </summary>
        public static string TrackStraightCircuit {
            get {
                return ResourceManager.GetString("TrackStraightCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Contact Track.
        /// </summary>
        public static string TrackStraightContact {
            get {
                return ResourceManager.GetString("TrackStraightContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Feeder.
        /// </summary>
        public static string TrackStraightFeeder {
            get {
                return ResourceManager.GetString("TrackStraightFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Isolating.
        /// </summary>
        public static string TrackStraightIsolating {
            get {
                return ResourceManager.GetString("TrackStraightIsolating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Uncoupler.
        /// </summary>
        public static string TrackStraightUncoupler {
            get {
                return ResourceManager.GetString("TrackStraightUncoupler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-Way Turnout.
        /// </summary>
        public static string TrackThreeWayTurnout {
            get {
                return ResourceManager.GetString("TrackThreeWayTurnout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Table.
        /// </summary>
        public static string TrackTransferTable {
            get {
                return ResourceManager.GetString("TrackTransferTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Turnout.
        /// </summary>
        public static string TrackTurnoutLeft {
            get {
                return ResourceManager.GetString("TrackTurnoutLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Turnout.
        /// </summary>
        public static string TrackTurnoutRight {
            get {
                return ResourceManager.GetString("TrackTurnoutRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turntable.
        /// </summary>
        public static string TrackTurntable {
            get {
                return ResourceManager.GetString("TrackTurntable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with a lantern.
        /// </summary>
        public static string TrackWithLantern {
            get {
                return ResourceManager.GetString("TrackWithLantern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Turnout.
        /// </summary>
        public static string TrackYTurnout {
            get {
                return ResourceManager.GetString("TrackYTurnout", resourceCulture);
            }
        }
    }
}
