name: Delivery Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 2
      matrix:
        build_platform: [x86, x64]

    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Setup to add MSBuild.exe to path"
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: "Download sandcastle"
      run: |
           $url = "https://github.com/EWSoftware/SHFB/releases/download/v2020.3.6.0/SHFBInstaller_v2020.3.6.0.zip"
           $output = "$env:GITHUB_WORKSPACE\Rail\SHFBInstaller_v2020.3.6.0.zip"
           (New-Object System.Net.WebClient).DownloadFile($url, $output)
           7z x -y SHFBInstaller_v2020.3.6.0.zip | Out-Null
           Write-Host "Installing MSI..."
           cmd /c start /wait msiexec /i InstallResources\SandcastleHelpFileBuilder.msi /quiet
           Write-Host "Installing VSIX..."
           . "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VSIXInstaller.exe" /q /a InstallResources\SHFBVisualStudioPackage_VS2017AndLater.vsix
           Write-Host "Sandcastle installed" -ForegroundColor Green
      shell: pwsh
      working-directory: .\Rail

    - name: "restore"
      working-directory: .
      run: msbuild Rail.sln /m /verbosity:minimal /t:restore /p:configuration="Release" /p:platform="${{ matrix.build_platform }}"

    - name: "MSBuild of solution"
      working-directory: .
      run: |
           $env:SHFBROOT = "C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\"
           msbuild Rail.sln /m /verbosity:minimal /p:configuration="Release" /p:platform="${{ matrix.build_platform }}"

    - name: "Archive artifacts"
      uses: actions/upload-artifact@v1
      with:
          name: Rail (${{ matrix.build_platform }})
          path: Rail.Installer\Installs\Rail-0.1.0.0-Release-${{ matrix.build_platform }}.msi
